version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /wt-checkout/backend
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /wt-checkout/backend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /wt-checkout
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /wt-iso/backend
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /wt-iso/backend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /wt-iso
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /wt-pnmp/backend
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /wt-pnmp/backend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /wt-pnmp
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /wt-setupnode/backend
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /wt-setupnode/backend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /wt-setupnode
    schedule:
      interval: daily
